import { useState } from 'react';
import { ArrowRight, FolderPlus, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import type { Catalog, Category, Collection } from '../types';
import { Modal } from '../components/Modal';
import { slugify } from '../lib/catalog';
import { ProductImage } from '../components/Image';
export function Organization({catalog,onChange,tab,notify}:{catalog:Catalog;onChange:(c:Catalog)=>void;tab:'categories'|'collections';notify:(m:string)=>void}){
 const [category,setCategory]=useState<Category>();const [collection,setCollection]=useState<Collection>();const [originalId,setOriginalId]=useState('');const [error,setError]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);
 const saveCategory=(e:React.FormEvent)=>{e.preventDefault();if(!category)return;try{if(catalog.categories.some(c=>c.id===category.id&&c.id!==originalId))throw new Error('That category ID is already in use.');onChange({...catalog,categories:originalId?catalog.categories.map(c=>c.id===originalId?category:c):[...catalog.categories,category]});setCategory(undefined);}catch(e){setError(e instanceof Error?e.message:'Please check the category.');}};
 const saveCollection=(e:React.FormEvent)=>{e.preventDefault();if(!collection)return;try{if(catalog.collections.some(c=>c.id===collection.id&&c.id!==originalId))throw new Error('That collection ID is already in use.');onChange({...catalog,collections:originalId?catalog.collections.map(c=>c.id===originalId?collection:c):[...catalog.collections,collection]});setCollection(undefined);}catch(e){setError(e instanceof Error?e.message:'Please check the collection.');}};
 const matches=catalog.products.filter(p=>p.title.toLowerCase().includes(search.toLowerCase())||p.sku.toLowerCase().includes(search.toLowerCase()));
 return <><div className="studio-section-heading"><div><span className="eyebrow">KEEP THE SHELVES IN ORDER</span><h1>{tab==='categories'?'Categories & subcategories':'Curated collections'}</h1><p>{tab==='categories'?'Give every good thing a home.':'Make it easier to shop for a meal, a moment, or the week.'}</p></div><button className="btn" onClick={()=>{setOriginalId('');setError('');if(tab==='categories')setCategory({id:'',name:'',description:'',image:'',color:'#edf0df',subcategories:[]});else{setCollection({id:`edit-${crypto.randomUUID().slice(0,8)}`,title:'',description:'',productIds:[]});setSearch('');setPage(1);}}}><Plus size={17}/> Add {tab==='categories'?'category':'collection'}</button></div>
 {tab==='categories'?<div className="studio-category-grid">{catalog.categories.map(c=><article key={c.id} className="studio-category-card"><div className="studio-category-top"><ProductImage src={c.image} alt={c.name}/><div><h2>{c.name}</h2><span>{catalog.products.filter(p=>p.category===c.id).length} products · {c.subcategories.length} subcategories</span></div></div><p>{c.description}</p><div className="subcategory-chips">{c.subcategories.map(s=><span key={s.id}>{s.name}</span>)}</div><div className="studio-card-actions"><button className="text-link" onClick={()=>{setError('');setOriginalId(c.id);setCategory(structuredClone(c));}}><Pencil size={14}/> Edit category</button><button className="icon-btn danger" aria-label={`Delete ${c.name}`} disabled={catalog.products.some(p=>p.category===c.id)} title="Move all products before deleting a category" onClick={()=>{onChange({...catalog,categories:catalog.categories.filter(x=>x.id!==c.id)});notify('Empty category removed.');}}><Trash2 size={16}/></button></div></article>)}</div>:<div className="studio-category-grid">{catalog.collections.map(c=><article key={c.id} className="studio-category-card"><FolderPlus size={30} strokeWidth={1.2}/><h2>{c.title}</h2><p>{c.description}</p><span className="small muted">{c.productIds.length} products in this edit</span><div className="studio-card-actions"><button className="text-link" onClick={()=>{setError('');setOriginalId(c.id);setCollection(structuredClone(c));setSearch('');setPage(1);}}><Pencil size={14}/> Edit collection</button><button className="icon-btn danger" aria-label={`Delete ${c.title}`} onClick={()=>{onChange({...catalog,collections:catalog.collections.filter(x=>x.id!==c.id)});notify('Collection removed; products are unchanged.');}}><Trash2 size={16}/></button></div></article>)}</div>}
 {category&&<Modal open onClose={()=>setCategory(undefined)} title={originalId?'Edit category':'A new shelf'}><form onSubmit={saveCategory}>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="form-grid"><label className="field">Category name *<input required value={category.name} onChange={e=>setCategory({...category,name:e.target.value,id:originalId?category.id:slugify(e.target.value)})}/></label><label className="field">Stable category ID *<input required value={category.id} readOnly={!!originalId} onChange={e=>setCategory({...category,id:e.target.value})}/></label><label className="field full-width">Description<input value={category.description} onChange={e=>setCategory({...category,description:e.target.value})}/></label><label className="field">Image URL or path<input value={category.image} onChange={e=>setCategory({...category,image:e.target.value})}/></label><label className="field">Background colour<input type="color" value={category.color} onChange={e=>setCategory({...category,color:e.target.value})}/></label></div><div className="editor-subheading"><h3>Subcategories</h3><button type="button" className="btn-secondary" onClick={()=>setCategory({...category,subcategories:[...category.subcategories,{id:`sub-${crypto.randomUUID().slice(0,6)}`,name:''}]})}><Plus size={14}/> Add subcategory</button></div>{category.subcategories.map((s,i)=><div className="subcategory-edit" key={s.id}><label className="field">Name<input required value={s.name} onChange={e=>setCategory({...category,subcategories:category.subcategories.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><small>ID: {s.id}</small></label><button type="button" className="icon-btn danger" aria-label={`Remove ${s.name||'subcategory'}`} disabled={catalog.products.some(p=>p.category===category.id&&p.subcategory===s.id)} onClick={()=>setCategory({...category,subcategories:category.subcategories.filter((_,j)=>i!==j)})}><Trash2 size={16}/></button></div>)}<p className="small muted">A subcategory can be removed after its products are moved elsewhere.</p><div className="form-actions"><button className="btn" type="submit">Save category to draft</button></div></form></Modal>}
 {collection&&<Modal open onClose={()=>setCollection(undefined)} title={originalId?'Edit collection':'Make a little collection'}><form onSubmit={saveCollection}>{error&&<p className="inline-error" role="alert">{error}</p>}<label className="field">Collection title *<input required value={collection.title} onChange={e=>setCollection({...collection,title:e.target.value})}/></label><label className="field">A short description<textarea value={collection.description} onChange={e=>setCollection({...collection,description:e.target.value})} rows={2}/></label><div className="editor-subheading"><h3>Pick your products</h3><span className="small muted">{collection.productIds.length} selected</span></div><div className="studio-search"><Search size={17}/><input aria-label="Find products for collection" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search products or SKU…"/></div><div className="collection-product-picker">{matches.slice((page-1)*15,page*15).map(p=><label className="collection-pick" key={p.id}><input type="checkbox" checked={collection.productIds.includes(p.id)} onChange={e=>setCollection({...collection,productIds:e.target.checked?[...collection.productIds,p.id]:collection.productIds.filter(id=>id!==p.id)})}/><span>{p.title}<small>{p.sku} · {p.unit}{!p.active?' · Archived':''}</small></span></label>)}</div><div className="pagination"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {Math.max(1,Math.ceil(matches.length/15))}</span><button type="button" disabled={page*15>=matches.length} onClick={()=>setPage(p=>p+1)}>Next <ArrowRight size={14}/></button></div><div className="form-actions"><button className="btn" type="submit">Save collection to draft</button></div></form></Modal>}</>;
}
