import { ArrowRight, ArrowUpRight, Leaf, MessageCircle, ShoppingBasket, Sparkles, Sprout } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useStore } from '../context';
import { Hero } from '../components/HeroExperience';
import { MarketRibbon, MarketEdits, EditorialImage } from '../components/MarketMotion';
import { ProductCard } from '../components/ProductCard';
import { ProductImage } from '../components/Image';
import { FAQ } from './Info';
export function Home() {
 const {config,meta,home}=useStore();
 return <><Hero/><MarketRibbon/><MarketEdits/>
 {config.sections.categories&&<section id="categories" className="section-shell categories-section" data-reveal><div className="section-heading"><div><div className="eyebrow">WANDER A LITTLE</div><h2>Follow your appetite.</h2></div><Link className="text-link" to="/shop">Shop everything <ArrowUpRight size={17}/></Link></div><div className="category-grid">{meta.categories.slice(0,6).map(c=><Link className="category-card" key={c.id} to={`/category/${c.id}`}><div className="category-image" style={{background:c.color}}><ProductImage src={c.image} alt={c.name}/><span className="category-arrow"><ArrowUpRight size={18}/></span></div><h3>{c.name}</h3></Link>)}</div><Link className="more-categories" to="/shop">Plus snacks, frozen favourites & things for the home <ArrowRight size={15}/></Link></section>}
 {config.sections.featured&&<section className="section-shell featured-section" data-reveal><div className="section-heading"><div><div className="eyebrow">MEET YOUR NEXT FAVOURITES</div><h2>Meet your next favourites.</h2></div><Link to="/shop?featured=1" className="text-link">See the full shelf <ArrowUpRight size={17}/></Link></div><div className="product-grid home-products">{home.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>}
 {config.sections.editorial&&<section className="editorial section-shell" data-reveal><EditorialImage src={config.hero.editorialImage || config.hero.image}/><div className="editorial-copy"><span className="eyebrow">FROM A FEW GOOD INGREDIENTS</span><h2>A little of this.<br/><em>A lovely meal.</em></h2><p>You don’t always need a recipe. A handful of vegetables, a good loaf, something to drizzle. Sometimes dinner is already in your basket.</p><Link className="btn" to="/shop?collection=tonights-dinner">Find tonight’s ingredients <ArrowRight size={18}/></Link><Sprout className="editorial-sprout" size={105} strokeWidth={.65}/></div></section>}
 {config.sections.collections&&<section className="section-shell collections-section" data-reveal><div className="section-heading"><div><div className="eyebrow">A LITTLE HELP WITH THE WEEK</div><h2>Less thinking. More cooking.</h2></div><span className="handwritten">Make yourself at home.</span></div><div className="collection-grid">{meta.collections.map((c,i)=><Link key={c.id} className={`collection-card collection-${i}`} to={`/shop?collection=${c.id}`}><span className="collection-number">0{i+1} / THE EVERYDAY EDIT</span><h3>{c.title}</h3><p>{c.description}</p><div className="collection-bottom"><span>Shop the edit <ArrowUpRight size={17}/></span>{i===0?<ShoppingBasket size={50} strokeWidth={1}/>:i===1?<Leaf size={50} strokeWidth={1}/>:<Sprout size={50} strokeWidth={1}/>}</div></Link>)}</div></section>}
 <section className="how-it-works section-shell" data-reveal><div className="section-heading"><div><div className="eyebrow">A GOOD SHOP. A SIMPLE CONVERSATION.</div><h2>Your basket. Our next conversation.</h2></div><Link to="/delivery" className="text-link">How ordering works <ArrowUpRight size={17}/></Link></div><div className="steps-grid">{[[ShoppingBasket,'Pick your good things.','Browse the shelves and add what you need to your basket.'],[MessageCircle,'Send a little hello.','Share your list on WhatsApp, with any questions or requests.'],[Sparkles,'We’ll take it from there.','Confirm availability, delivery, and the final total with the store.']].map(([Icon,title,text],i)=>{const I=Icon as typeof ShoppingBasket;return <div className="step" key={i}><span className="step-icon"><I size={25} strokeWidth={1.3}/></span><div><span className="step-number">0{i+1}</span><h3>{title as string}</h3><p>{text as string}</p></div></div>;})}</div></section>
 {config.sections.faq&&<section className="home-faq section-shell" data-reveal><div><div className="eyebrow">BEFORE YOU FILL YOUR BASKET</div><h2>A few useful<br/><em>little answers.</em></h2><Link to="/faq" className="text-link">All your questions <ArrowUpRight size={17}/></Link></div><FAQ compact/></section>}</>;
}
