import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Mail, MapPin, MessageCircle, Plus, ShoppingBasket, Sprout } from 'lucide-react';
import { useStore } from '../context';
import { whatsappLink } from '../lib/catalog';
import { WhatsAppIcon } from '../components/Layout';
import { CartContent } from '../components/Cart';
const answers=[
 ['How do I place an order?','Add your groceries to the basket, then choose “Send order enquiry on WhatsApp.” Review and send the prepared message. The store will confirm the items, delivery details, and final total with you.'],
 ['Where do you deliver?','Delivery areas and charges are confirmed by the store. Get in touch before sending your basket if you would like to check your area.'],
 ['Can I ask for a different pack size?','Of course. Choose an available size on the product page, or add a note to your basket. The store can let you know which options are available.'],
 ['Is adding something to my basket a reservation?','Your basket is a shopping list. Stock is not reserved, and opening WhatsApp does not confirm an order. The store confirms availability with you.'],
 ['Why might the final price be different?','Loose produce is priced by its final weight. Delivery charges and any substitutions are also confirmed in your WhatsApp conversation before the order is agreed.'],
 ['Will my basket still be here later?','Your basket and favourites are saved in this browser when browser storage is available. Clearing browsing data removes them, and they are not shared across devices.'],
 ['Can I change something after sending my list?','Reply in the same WhatsApp conversation and tell the store what you would like to change. They will confirm whether the change can be made.'],
];
export function FAQ({compact=false}:{compact?:boolean}){return <div className="faq-list">{answers.slice(0,compact?3:undefined).map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div>;}
export function About(){const {config}=useStore();return <div className="section-shell info-page"><div className="eyebrow">A PLACE FOR THE EVERYDAY</div><h1>Good food belongs<br/><em>in everyday life.</em></h1><div className="about-layout"><img src={config.hero.image} alt="A paper grocery bag filled with vegetables and bread on a sunlit table" width="1536" height="1024"/><div><h2>A little more thought.<br/>A little less fuss.</h2><p>A full fridge isn’t the whole story. It’s breakfast before a busy day. Something warm at the end of it. A table with room for one more.</p><p>That’s the idea behind {config.brand}: a simple place to find the groceries you need, with a little inspiration along the way.</p><p>Browse at your own pace. Keep your favourites close. And when you’re ready, start a conversation with the store.</p><Link className="btn" to="/shop">Find your good things <ArrowRight size={18}/></Link></div></div>{config.demo&&<p className="demo-note">This is a demonstration storefront. The brand, catalog, imagery, and prices are illustrative.</p>}</div>;}
export function Contact(){const {config}=useStore();const link=whatsappLink(config.whatsapp,`Hello ${config.brand}! I have a question about your groceries.`);return <div className="section-shell info-page contact-page"><div className="eyebrow">PULL UP A CHAIR</div><h1>Let’s talk<br/><em>groceries.</em></h1><p className="info-lead">A question about an ingredient, a different pack size, or what’s possible for your next shop. Start here.</p><div className="contact-grid"><div className="contact-main"><WhatsAppIcon size={40}/><h2>A little hello goes a long way.</h2><p>Message the store to check availability, ask about delivery, or share your grocery list.</p>{link?<a className="btn" href={link} target="_blank" rel="noopener noreferrer">Chat on WhatsApp <ArrowUpRight size={18}/></a>:<div className="notice">We’re setting the table. WhatsApp contact will be available when the store opens. You can explore the shelves and make a list in the meantime.</div>}<Link className="text-link" to="/shop">Back to the shelves <ArrowRight size={16}/></Link></div><div className="contact-details"><div><MapPin size={24}/><h3>Your neighbourhood</h3><p>{config.serviceArea||'Delivery areas will be shared when the store opens.'}</p></div>{config.email&&<div><Mail size={24}/><h3>Drop us a line</h3><a href={`mailto:${config.email}`}>{config.email}</a></div>}<div><ShoppingBasket size={24}/><h3>Already have a list?</h3><p>Your basket turns into a message with all the useful details.</p><Link className="text-link" to="/cart">Open your basket <ArrowRight size={15}/></Link></div></div></div></div>;}
export function Delivery(){const {config}=useStore();return <div className="section-shell info-page narrow-page"><div className="eyebrow">FROM YOUR BASKET TO A CONVERSATION</div><h1>A simple way<br/><em>to shop.</em></h1><div className="info-steps">{[[ShoppingBasket,'Make your list','Explore the shelves, choose your pack sizes, and add what you need. Your basket stays in this browser.'],[MessageCircle,'Say hello on WhatsApp','The basket prepares a message with your items, quantities, and estimated subtotal. You review it and send it yourself.'],[Sprout,'Agree the details','The store confirms availability, any substitutions, delivery charges, payment arrangements, and the final total.']].map(([Icon,title,text],i)=>{const I=Icon as typeof Sprout;return <article key={i}><I size={27} strokeWidth={1.2}/><div><h2>{title as string}</h2><p>{text as string}</p></div></article>;})}</div><div className="delivery-note"><h2>About delivery</h2><p>{config.deliveryNote}</p>{config.serviceArea&&<p>Service area: {config.serviceArea}</p>}<Link to="/contact" className="text-link">Ask the store <ArrowUpRight size={16}/></Link></div><h2>A few useful answers</h2><FAQ/></div>;}
export function FAQPage(){return <div className="section-shell info-page narrow-page"><div className="eyebrow">THE USEFUL LITTLE DETAILS</div><h1>You asked.<br/><em>Here’s the good stuff.</em></h1><FAQ/><div className="faq-contact"><p>Still have something on your mind?</p><Link className="btn" to="/contact">Let’s talk <ArrowRight size={17}/></Link></div></div>;}
export function Privacy(){return <div className="section-shell info-page narrow-page"><div className="eyebrow">YOUR BROWSER. YOUR BASKET.</div><h1>A little about<br/><em>your data.</em></h1><div className="prose"><h2>What this storefront saves</h2><p>Your basket, favourites, and previous basket list are kept in this browser’s local storage. They are not stored in a customer database or synced between devices. Clearing this site’s browser data removes them.</p><h2>When you choose WhatsApp</h2><p>Your grocery list and any note you write are included in the WhatsApp link when you choose to open it. You review and send the message in WhatsApp, which is a separate service. Avoid putting sensitive personal information in basket notes.</p><h2>Payments and accounts</h2><p>This storefront does not collect payment details, create customer accounts, or confirm orders. The store agrees order and payment details directly with you.</p><h2>Images and hosting</h2><p>The included images and fonts are served with the site. If the store later uses external image links, loading those images makes a request to that image provider. The hosting provider may keep ordinary connection logs.</p><p className="notice">This describes the current demonstration implementation. The store owner should review the information for their actual hosting and business practices before launch.</p></div></div>;}
export function CartPage(){return <div className="section-shell info-page cart-page"><div className="eyebrow">ROOM FOR GOOD THINGS</div><h1>Your basket.</h1><CartContent/></div>;}
export function NotFound(){return <div className="section-shell empty-state not-found"><Sprout size={60} strokeWidth={1}/><div className="eyebrow">A LITTLE OFF THE BEATEN AISLE</div><h1>This shelf isn’t here.</h1><p>There are plenty of good things back at the market.</p><Link className="btn" to="/shop">Back to the shelves <ArrowRight size={17}/></Link></div>;}
