import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Copy, Download, Minus, Plus, ShoppingBasket, Trash2 } from 'lucide-react';
import { useStore } from '../context';
import { cartKey, cartTotal, orderMessage, whatsappLink } from '../lib/catalog';
import { download } from '../lib/files';
import { ProductImage } from './Image';
import { WhatsAppIcon } from './Layout';
export function CartContent({ onContinue=()=>{} }: {onContinue?:()=>void}) {
 const {cart,setQuantity,remove,config,format,notify,rememberBasket,refreshCart}=useStore();const [notes,setNotes]=useState(''); const [copied,setCopied]=useState(false);const [busy,setBusy]=useState(false);const message=orderMessage(cart,config.brand,config.currency,notes);const link=whatsappLink(config.whatsapp,message);const long=!!link&&link.length>1900;
 async function send() {setBusy(true);try{ const current=await refreshCart(); if(!current.length)return;const prepared=orderMessage(current,config.brand,config.currency,notes);const url=whatsappLink(config.whatsapp,prepared);if(!url){notify('WhatsApp ordering will be available when the store adds its number. You can still copy your basket.');return;}rememberBasket();window.open(url.length>1900?whatsappLink(config.whatsapp,`Hello ${config.brand}! I have a grocery list to share.`)!:url,'_blank','noopener,noreferrer');}catch(e){notify(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 if(!cart.length)return <div className="empty-state"><div className="empty-icon"><ShoppingBasket size={42} strokeWidth={1.2}/></div><h3>A little room for good things.</h3><p>Your basket is waiting for its first find.</p><Link className="btn" to="/shop" onClick={onContinue}>Explore the shelves <ArrowRight size={18}/></Link></div>;
 return <div className="cart-content"><p className="cart-intro">A few good things for your kitchen.</p><div className="cart-items">{cart.map(item=><article className="cart-item" key={cartKey(item)}><ProductImage src={item.image} alt={item.title}/><div className="cart-item-info"><h3>{item.title}</h3><p>{item.unit} <span>· {format(item.price)} each</span></p><div className="quantity-control"><button aria-label={`Decrease ${item.title}`} onClick={()=>setQuantity(cartKey(item),item.quantity-1)}><Minus size={14}/></button><span aria-label={`Quantity of ${item.title}`}>{item.quantity}</span><button aria-label={`Increase ${item.title}`} onClick={()=>setQuantity(cartKey(item),item.quantity+1)}><Plus size={14}/></button></div></div><div className="cart-item-end"><strong>{format(item.price*item.quantity)}</strong><button className="icon-btn" aria-label={`Remove ${item.title}`} onClick={()=>remove(cartKey(item))}><Trash2 size={16}/></button></div></article>)}</div><label className="field cart-notes">Anything we should know?<textarea placeholder="A different pack size, a question, a little note…" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} rows={2}/></label><div className="cart-summary"><span>Estimated subtotal</span><strong>{format(cartTotal(cart))}</strong></div><p className="muted small">Availability, delivery charges, and the final total are confirmed by the store. Prices for loose produce may change with the final weight.</p>{long&&<p className="notice">This is a generous basket. Copy or download your full list, then paste or attach it in WhatsApp.</p>}<button className="btn whatsapp-order" onClick={send} disabled={busy}><WhatsAppIcon size={21}/>{busy?'Checking your basket…':'Send order enquiry on WhatsApp'}</button>{!link&&<p className="small muted">This preview isn’t accepting orders yet. Your basket can still be saved as a list.</p>}<div className="cart-utilities"><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{download(message,'my-grocery-list.txt','text/plain');}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy list'}</button><button className="text-link" onClick={()=>download(message,'my-grocery-list.txt','text/plain')}><Download size={15}/> Download list</button></div><p className="small muted cart-disclaimer">You review and send the message in WhatsApp. Your basket stays here.</p></div>;
}
