import { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Heart, Menu, Search, ShoppingBasket, Sprout, X } from 'lucide-react';
import { useStore } from '../context';
import { CartContent } from './Cart';
import { Modal } from './Modal';
import { ProductImage } from './Image';
import type { SearchItem } from '../types';
import { whatsappLink } from '../lib/catalog';
export function WhatsAppIcon({ size = 22 }: {size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20.6 11.7a8.6 8.6 0 0 1-12.8 7.5L3 20.5l1.3-4.6a8.6 8.6 0 1 1 16.3-4.2Z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/><path d="M8.3 7.5c-.6.3-.9 1.1-.7 1.9.6 2.6 2.6 4.7 5.2 5.4.9.3 1.9.1 2.2-.6l.4-.9c.1-.2 0-.4-.2-.5l-1.6-.8c-.2-.1-.4 0-.5.2l-.6.7c-.1.1-.3.2-.5.1-1.3-.5-2.3-1.5-2.8-2.7-.1-.2-.1-.3.1-.5l.6-.6c.1-.2.2-.4.1-.6l-.8-1.7c-.1-.2-.3-.2-.5-.2l-.4.1Z" fill="currentColor"/></svg>; }
export function Brand({ inverse=false }: {inverse?:boolean}) { const {config}=useStore();return <Link className={`brand ${inverse?'inverse':''}`} to="/" aria-label={`${config.brand} home`}><ShoppingBasket size={34} strokeWidth={1.4}/><span>{config.brand}<small>THE EVERYDAY GROCERY</small></span></Link>; }
export function Layout() {
 const {config,cart,cartOpen,setCartOpen,favorites,getIndex,format}=useStore(); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(''); const [suggestions,setSuggestions]=useState<SearchItem[]>([]); const [focused,setFocused]=useState(false);const navigate=useNavigate();const location=useLocation();
 useEffect(()=>{setMobile(false);setFocused(false);},[location.pathname,location.search]);
 useEffect(()=>{ if(query.trim().length<2){setSuggestions([]);return;} let alive=true; const t=setTimeout(()=>{getIndex().then(d=>{if(alive)setSuggestions(d.products.filter(p=>p.search.includes(query.toLowerCase().trim())).slice(0,5));}).catch(()=>{});},180);return()=>{alive=false;clearTimeout(t);};},[query,getIndex]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[location.pathname]);
 const whatsapp=whatsappLink(config.whatsapp,`Hello ${config.brand}! I'd like to ask about your groceries.`);
 const contact=()=>{if(whatsapp)window.open(whatsapp,'_blank','noopener,noreferrer');else navigate('/contact');};
 return <><a className="skip-link" href="#main">Skip to content</a><div className="announcement"><span><Sprout size={14}/>{config.announcement}</span><Link to="/contact">Let’s talk groceries <ArrowUpRight size={13}/></Link></div>
 <header className="header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{config.navigation.map(n=><NavLink key={n.href} to={n.href} end={n.href==='/'}>{n.label}</NavLink>)}</nav><div className="header-actions"><form className="header-search" role="search" onSubmit={e=>{e.preventDefault();navigate(`/shop?q=${encodeURIComponent(query.trim())}`);setFocused(false);}}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),180)} aria-label="Search groceries" placeholder="Find something good…" autoComplete="off"/>{focused&&query.trim().length>1&&<div className="search-suggestions">{suggestions.map(p=><Link to={`/product/${p.slug}`} key={p.id}><ProductImage src={p.image} alt={p.title}/><span>{p.title}<small>{p.unit}</small></span><strong>{format(p.price)}</strong></Link>)}<button type="submit">{suggestions.length?'See all results':'Search the shelves'} <ArrowRight size={16}/></button></div>}</form><Link className="icon-btn favorites-link" to="/shop?favorites=1" aria-label={`Favourites, ${favorites.length} saved`}><Heart size={21}/>{favorites.length>0&&<span className="mini-count">{favorites.length}</span>}</Link><button className="header-basket" onClick={()=>setCartOpen(true)} aria-label={`Open basket, ${cart.reduce((n,x)=>n+x.quantity,0)} items`}><ShoppingBasket size={21}/><span>Basket</span><b>{cart.reduce((n,x)=>n+x.quantity,0)}</b></button><button className="icon-btn mobile-menu-button" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={23}/></button></div></div></header>
 <main id="main"><Outlet/></main><footer className="footer"><div className="footer-top section-shell"><div className="footer-brand"><Brand inverse/><p>For everyday meals.<br/>And the moments around them.</p><span className="handwritten">See you at the table.</span></div><div><h3>Explore the shelves</h3><Link to="/shop">All groceries</Link><Link to="/category/fruit">Fruit & vegetables</Link><Link to="/category/pantry">Cupboard essentials</Link><Link to="/shop?favorites=1">Your favourites</Link></div><div><h3>A little help</h3><Link to="/about">Our story</Link><Link to="/delivery">Delivery & ordering</Link><Link to="/faq">Frequently asked</Link><Link to="/contact">Get in touch</Link></div><div className="footer-contact"><h3>Let’s talk groceries.</h3><p>Looking for something?<br/>We’re a message away.</p><button onClick={contact}><WhatsAppIcon size={20}/> Chat on WhatsApp <ArrowUpRight size={15}/></button></div></div><div className="footer-bottom section-shell"><span>© {new Date().getFullYear()} {config.brand}</span><span>{config.demo?'Demo store · Illustrative products & prices':'Good food. Good days.'}</span><Link to="/privacy">Privacy & your data</Link></div></footer>
 {!cartOpen&&<button className="whatsapp-float" onClick={contact} aria-label="Contact us on WhatsApp"><WhatsAppIcon size={26}/><span>Let’s chat</span></button>}
 <Modal open={cartOpen} onClose={()=>setCartOpen(false)} title="Your basket" className="drawer cart-drawer"><CartContent onContinue={()=>setCartOpen(false)}/></Modal>
 <Modal open={mobile} onClose={()=>setMobile(false)} title="Around the market" className="drawer mobile-navigation"><nav>{config.navigation.map(n=><Link key={n.href} to={n.href}>{n.label}<ArrowUpRight/></Link>)}<Link to="/shop?favorites=1">Your favourites <Heart/></Link><Link to="/contact">Get in touch <ArrowUpRight/></Link></nav><button className="btn" onClick={()=>{setMobile(false);setCartOpen(true);}}>Open your basket <ShoppingBasket size={20}/></button></Modal></>;
}
